#**Introduction and applications to data processing**



## Introduction to Numpy 
## NumpyArray Indexing 
## NumpyArray Operations 
## Broadcasting
## Data Processing 



#**A.Introduction**
####Numpy (Numeric Python): là một thư viện toán học phổ biến và mạnh mẽ của Python. Cho phép làm việc hiệu quả với ma trận và mảng, đặc biệt là dữ liệu ma trận và mảng lớn với tốc độ xử lý nhanh hơn nhiều lần khi chỉ sử dụng “core Python” đơn thuần.

##**1.Numpy is a Python library**


###**a.Khởi tạo mảng một chiều** **bold text**


In [ ]:
#Khởi tạo mảng một chiều với kiểu dữ liệu các phần tử là Integer
arr = np.array([1,3,4,5,6], dtype = int)

#Khởi tạo mảng một chiều với kiểu dữ liệu mặc định
arr = np.array([1,3,4,5,6])

print(arr)

[1 3 4 5 6]


###**b.Khởi tạo mảng hai chiều**

In [ ]:
arr1 = np.array([(4,5,6), (1,2,3)], dtype = int)

print(arr1)

[[4 5 6]
 [1 2 3]]


###**c.Khởi tạo mảng ba chiều**

In [ ]:
arr2 = np.array(([(2,4,0,6), (4,7,5,6)],
                 [(0,3,2,1), (9,4,5,6)],
                 [(5,8,6,4), (1,4,6,8)]), dtype = int)

print(arr2)

[[[2 4 0 6]
  [4 7 5 6]]

 [[0 3 2 1]
  [9 4 5 6]]

 [[5 8 6 4]
  [1 4 6 8]]]


###**d.Khởi tạo với các hàm có sẵn**
+ np.zeros((3,4), dtype = int): Tạo mảng hai chiều các phần tử 0 với kích thước 3x4.

In [ ]:
a = np.zeros((3,4), dtype = int)
print(a)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]


+ np.ones((2,3,4), dtype = int): Tạo mảng 3 chiều các phần tử 1 với kích thước 2x3x4.

In [ ]:
a = np.ones((2,3,4), dtype = int)
print(a)

[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]


+ np.arange(1,7,2): Tạo mảng với các phần tử từ 1 - 6 với bước nhảy là 2.

In [ ]:
a = np.arange(1,7,2)
print(a)

[1 3 5]


+ np.full((2,3),5): Tạo mảng 2 chiều các phần tử 5 với kích thước 2x3.

In [ ]:
import numpy as np
a = np.full((2,3),5)
print(a)

[[5 5 5]
 [5 5 5]]


+ np.eye(4, dtype=int): Tạo ma trận đơn vị với kích thước là 4x4.

In [ ]:
import numpy as np
a = np.eye(4,dtype=int)
print(a)

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


+ np.random.random((2,3)): Tạo ma trận các phần tử ngẫu nhiên với kích thước 2x3.

In [ ]:
a = np.random.random((2,3))
print(a)

[[0.92776432 0.45885918 0.09147678]
 [0.90993217 0.58214092 0.7596122 ]]


##**2.Thao tác với mảng**

+ dtype: Kiểu dữ liệu của phần tử trong mảng.
+ shape: Kích thước của mảng.
+ size: Số phần tử trong mảng.
+ ndim: Số chiều của mảng.

+ print("Kiểu dữ liệu của phần tử trong mảng:", arr2.dtype)
+ print("Kích thước của mảng:", arr2.shape)
+ print("Số phần tử trong mảng:", arr2.size)
+ print("Số chiều của mảng:", arr2.ndim)

In [ ]:
import numpy as np 
arr2 = np.random.random((2,3))
print(arr2)
print("Kiểu dữ liệu của phần tử trong mảng:", arr2.dtype)
print("Kích thước của mảng:", arr2.shape)
print("Số phần tử trong mảng:", arr2.size)
print("Số chiều của mảng:", arr2.ndim)
print('----------------------------------------------------')
arr2 = np.ones((2,3,4), dtype = int)
print(arr2)
print("Kiểu dữ liệu của phần tử trong mảng:", arr2.dtype)
print("Kích thước của mảng:", arr2.shape)
print("Số phần tử trong mảng:", arr2.size)
print("Số chiều của mảng:", arr2.ndim)

[[0.55283912 0.55977965 0.86513833]
 [0.8061266  0.62833522 0.39042481]]
Kiểu dữ liệu của phần tử trong mảng: float64
Kích thước của mảng: (2, 3)
Số phần tử trong mảng: 6
Số chiều của mảng: 2
----------------------------------------------------
[[[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]

 [[1 1 1 1]
  [1 1 1 1]
  [1 1 1 1]]]
Kiểu dữ liệu của phần tử trong mảng: int64
Kích thước của mảng: (2, 3, 4)
Số phần tử trong mảng: 24
Số chiều của mảng: 3


+ Truy cập phần tử trong mảng

#####Các phần tử trong mảng được đánh số từ 0 trở đi

+ arr[i]: Truy cập tới phần tử thứ i của mảng 1 chiều.
+ arr1[i,j]: Truy cập tới phần tử hàng i, cột j của mảng 2 chiều.
+ arr2[n,i,j]: Truy cập tới phần tử chiều n, hàng i, cột j của mảng 3 chiều.
+ arr[a:b]: Truy cập tới các phần tử từ a đến b-1 trong mảng 1 chiều.
+ arr1[:,:i]: Truy cập tới phần tử từ cột 0 đến cột i-1, của tất cả các hàng trong mảng 2 chiều.

In [ ]:
import numpy as np
arr2 = np.array(([(2,4,0,6), (4,7,5,6)],
                 [(0,3,2,1), (9,4,5,6)],
                 [(5,8,6,4), (1,4,6,8)]), dtype = int)
arr1 = np.array([(4,5,6), (1,2,3)], dtype = int)
arr = np.array([1,3,4,5,6])

print(arr2)
print("arr[2]=", arr[2])
print("arr1[1:2]=", arr1[1,2])
print("arr2[1,2,3]=", arr2[1,1,3])
print("arr[0:3]=", arr[0:3])
print("arr1[:,:1]=", arr1[:,:2])

[[[2 4 0 6]
  [4 7 5 6]]

 [[0 3 2 1]
  [9 4 5 6]]

 [[5 8 6 4]
  [1 4 6 8]]]
arr[2]= 4
arr1[1:2]= 3
arr2[1,2,3]= 6
arr[0:3]= [1 3 4]
arr1[:,:1]= [[4 5]
 [1 2]]


In [14]:
from google.colab import auth
auth.authenticate_user()
from pydrive.drive import GoogleDrive
from pydrive.auth import GoogleAuth
from oauth2client.client import GoogleCredentials
import numpy.core.defchararray as np_f
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
import numpy as np
#đây là chuỗi ký tự chữ và số dài xuất hiện khi bạn nhấp vào "lấy liên kết để chia sẻ"
myfile = drive.CreateFile({'id': '1Zw6LIV5b6XzCPONtrsyyg9LfqglNfCqQ'})
myfile.GetContentFile('Diem_2A.txt')
diem_2a = np.genfromtxt('Diem_2A.txt', dtype = int, delimiter=',') 

#ở đây tất cả phần tử là số nguyên nên mình để kiểu int cho dễ nhìn, các phần tử phân tách nhau bởi dấu ","
print("File dữ liệu điểm lớp 2A:\n", diem_2a)

File dữ liệu điểm lớp 2A:
 [[ 2  4  3  7  5  6  5  6  8  9  3  6  1  9  8  7  3  3  9  5  1  6  5  1
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]
 [ 1 10  4  9  6  9  0  2  3  1  8  6  8  4  2  9  2  9  5  0  4  1  7  3
  -1]
 [ 6  3  0  8  3  7  7  2  6  8  7  3  4  1  5  9  2  9  5  9  0  4  1  4
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]
 [ 3  5  3 10  9  1  9  8  3  1  6  0  7  0  8  5  2  7  7  1  1  6  1  6
  -1]]


**Các hàm thống kê**

In [15]:
arr = np.array([1,3,4,5,6])
arr1 = np.array([(4,5,6), (1,2,3)], dtype = int)
arr2 = np.array(([(2,4,0,6), (4,7,5,6)],
                 [(0,3,2,1), (9,4,5,6)],
                 [(5,8,6,4), (1,4,6,8)]), dtype = int)

+ arr.max() hoặc np.max(arr): Lấy giá trị lớn nhất của mảng arr.

In [22]:
print("Giá trị lớn nhất của mảng arr là:", np.max(arr))

Giá trị lớn nhất của mảng arr là: 6


+ arr.min() hoặc np.min(arr): Lấy giá trị nhỏ nhất của mảng arr.

In [19]:
print("Giá trị nhỏ nhất của mảng arr là:", np.min(arr))

Giá trị nhỏ nhất của mảng arr là: 1


+ arr.sum() hoặc np.sum(arr): Tổng tất cả các phần tử trong mảng arr.

In [20]:
print("Tổng tất cả các phần tử của mảng arr là:", np.sum(arr))

Tổng tất cả các phần tử của mảng arr là: 19


+ arr.mean() hoặc np.mean(arr): Trung bình cộng của tất cả các phần tử trong mảng arr.

In [ ]:
print("Trung bình cộng tất cả các phần tử của mảng arr là:", np.mean(arr))

+ np.median(arr): Trả về giá trị trung vị của mảng arr

In [21]:
print("Giá trị trung vị của mảng arr là:", np.median(arr))

Giá trị trung vị của mảng arr là: 4.0


![](https://i.imgur.com/VifTJQl.jpg)

![](https://i.imgur.com/aPv9KAx.jpg)

###c.Numpy array       Tensor in Tensorflow and Pytorch


In [23]:
import tensorflow as tf
import numpy as np
#create a numpy array 
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)

print('------------------------------------------------')
#convert from numpy array to tensor
arr_tf = tf.convert_to_tensor(arr_np)
print(arr_tf)
print(arr_tf.shape)
print('------------------------------------------------')
#convert from tensor to numpy array
arr_np_back = arr_tf.numpy()
print(arr_np_back)
print(arr_np_back.shape)


[0 1 2 3 4 5 6 7 8 9]
(10,)
------------------------------------------------
tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
(10,)
------------------------------------------------
[0 1 2 3 4 5 6 7 8 9]
(10,)


##3.Numpy arrays are multi-dimensional arrays






**Create Numpy array**

**From List**




> ### **arr_np = np.array(python_list)**



In [ ]:
import numpy as np
#tao list 
l = list(range(1,4))
#tao adarray
data = np.array(l)
print(data)
print(data[0])
print(data[1])

[1 2 3]
1
2


**Common attributes**


> dtype: data type


> shape: return a tuple of #elements in each dimension 


> ndim: return #dimensions









In [ ]:
import numpy as np
#tao list
list1D = [1,2,3]
#Tạo ndarray
data = np.array(list1D)
print(data)
print(data.shape)

[1 2 3]
(3,)


In [ ]:
import numpy as np
#tao list 
list2D = [[1,2],[3,4],[5,6]]
#tao ndaarray
data = np.array(list2D)
print(data)
print(data.shape)

[[1 2]
 [3 4]
 [5 6]]
(3, 2)


In [24]:
import numpy as np
#tao list
list3D = [[[1,6],[2,2],[3,4]],
          [[4,7],[5,2],[6,5]],
          [[7,7],[8,2],[9,7]]]
#tao ndaarray
data = np.array(list3D)
# hien thi data
print(data.shape)

(3, 3, 2)


**dtype example**


In [25]:
import numpy as np
# tao ndarray 
data1 = np.array([1,2,3],dtype=np.int32)
print(data1.dtype)

data2 = np.array([1.,2.,3.])
print(data2.dtype)

data3 = np.array([1,2,3],dtype=np.int64)
print(data3.dtype)


int32
float64
int64


**Update an element**


In [26]:
import numpy as np
#tao list 
l = list(range(1,4))
#tao ndarray 
data = np.array(l)
print(data)
data[0] = 8
print(data)


[1 2 3]
[8 2 3]


**zeros() function**

In [27]:
#Tao mot numpy array
#voi tat ca cac phan tu la 0
import numpy as np
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


**ones() function**

In [ ]:
import numpy as np
#numpy.ones(shape)
#shape: 2 dong , 3 cot
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


**full() function**

In [ ]:
import numpy as np
# numpy. full(shape,full value)
# shape: 2 dong ,3 cot
arr = np.full((2,3),9)
print(arr)

[[9 9 9]
 [9 9 9]]


**arange () function**


In [ ]:
import numpy as np
arr1 = [0,1,2,3,4]
arr2 = [0,2,4]
#np.arange(start =0 ,stop,step =1)
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(0,5,2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


**eye() function**

In [ ]:
#Tạo một numpy array với đường chéo là số 1
#Số 0 được điền vào những ô phần tử còn lại
import numpy as np
#numpy.eye(N)
#shape: 3 dòng , 3 cột
arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


**random() function**

In [ ]:
#np.random.random(size)
#shape : 2 dong,3 cot với
#phần tử có giá trị ngẫu nhiên
import numpy as np
arr = np.random.random((2,3))
print(arr)

[[0.43000759 0.91661254 0.85054511]
 [0.09119754 0.51135025 0.66846723]]


# **Some important functions**


**where() function**


In [28]:
import numpy as np
#create an array
arr = np.arange(5)
print(arr)
#condition
condition = arr<3
out = np.where(condition,arr,arr*2)
print(condition)
print(out)

[0 1 2 3 4]
[ True  True  True False False]
[0 1 2 6 8]


**flatten() function**


In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4]])
out = arr.flatten()
print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


**reshape() function**


In [ ]:
import numpy as np
#tạo list
l = [[1,2,3],[4,5,6]]
# tạo ndarray
data = np.array(l)
print('data\n',data)
print('data shape\n',data.shape)
#reshape 
data_rs = np.reshape(data,(3,2))
print('data_rs\n',data_rs)
print('data_rs shape\n',data_rs.shape)

data
 [[1 2 3]
 [4 5 6]]
data shape
 (2, 3)
data_rs
 [[1 2]
 [3 4]
 [5 6]]
data_rs shape
 (3, 2)


#**B.NumpyArray Indexing**

##**1.Slicing**

####**arr[for_axis_0, for_axis_1, …]**



![](https://i.imgur.com/efLdL2N.jpg)

![](https://i.imgur.com/uZj92SE.jpg)

In [ ]:
import numpy as np
#khỏi tạo numpy array a_arr
a_arr = np.array([[1,2,3],[5,6,7]])
#Sử dụng slicing để tạo mảng b_arr
#bằng cách lấy tất cả các dòng và cột 1,2
b_arr = a_arr[:,1:3]

print(a_arr)
print(b_arr)

[[1 2 3]
 [5 6 7]]
[[2 3]
 [6 7]]


**Mutable**

![](https://i.imgur.com/6JnrSBP.jpg)

In [ ]:
import numpy as np
#Khởi tạo numpy array a_arr
a_arr = np.array([[1,2,3],[5,6,7]])
print('a_arr \n',a_arr)

#Sử dụng slicing để tạo mảng b_arr
b_arr = a_arr[:,1:3]
print('b_arr \n',b_arr)
print('Before changing \n',a_arr[0,1])
b_arr[0,0] = 99
print('After changing \n',a_arr[0,1])

a_arr 
 [[1 2 3]
 [5 6 7]]
b_arr 
 [[2 3]
 [6 7]]
Before changing 
 2
After changing 
 99


 **Get a row**


![](https://i.imgur.com/C1cL0ML.jpg)

In [ ]:
import numpy as np
# tạo một numpy array có shape (3,3) với giá trị 
# [[1 2 3],[5 6 7],[9 10 11]]
# 
#

In [ ]:
arr = np.array([[1,2,3],[5,6,7],[9,10,11]])
#Hai cách truy cập dữ liệu ở dòng index = 1
#cách 1 : só chiều giảm
row_m1 = arr[1,:]
#cách 2 : số chiều được giứ nguyên
row_m2 = arr[1:2,:]
print(row_m1,row_m1.shape)
print(row_m1,row_m2.shape)

[5 6 7] (3,)
[5 6 7] (1, 3)


**Get a column**


![](https://i.imgur.com/Rl7oiuv.jpg)

In [ ]:
import numpy as np
#Tạo một numpy array có shape (3,3) với giá trị
arr = np.array([[1,2,3],[5,6,7],[9,10,11]])
#hai cách truy cập dữ liệu ở cột index = 1 của mảng
# cách 1 : Số chiều giảm
col_m1 = arr[:,1]
# cách 2 : số chiều được giữa nguyên 
col_m2 = arr[:,1:2]
print(col_m1,col_m1.shape)
print(col_m2,col_m2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


**Using Lists as indices**


![](https://i.imgur.com/us8i29e.jpg)

In [ ]:
import numpy as np
#tạo arr
arr = np.array([[1,2],[3,4],[5,6]])
#Lấy giá trị vị trí (0,0) , (1,1) và (2,0)
out1 = arr[[0,1,2],[0,1,0]]
print('out1:\n',out1)
#Có thể truy xuất tới 1 phần tử nhiều hơn 1 lần 
out2 = arr[[0,0],[1,1]]
print('out2:\n',out2)

out1:
 [1 4 5]
out2:
 [2 2]


**Boolean indices**


![](https://i.imgur.com/2lUa85e.jpg)

In [ ]:
import numpy as np
arr = np.array([[1,2],[3,4],[5,6]])
print(arr)
#Tìm các phần tử lớn hơn 2
bool_idx = (arr>2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


#**C.NumpyArray Operations**


**Addition**


![](https://i.imgur.com/7OTjMQz.jpg)

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print("data x\n",x)
print("data y\n",y)
#Tổng của 2 màng
print('method 1 \n',x+y)
print('method 2 \n',np.add(x,y))

data x
 [1 2 3 4]
data y
 [5 6 7 8]
method 1 
 [ 6  8 10 12]
method 2 
 [ 6  8 10 12]


 **Subtraction**


![](https://i.imgur.com/jlXYbiO.jpg)

In [ ]:
import numpy as np
x = np.array([5,6,7,8])
y = np.array([1,2,3,4])
print('data x \n',x)
print('data y \n',y)
#Hiệu của hai mảng 
print('method 1 \n',x-y)
print('method 2 \n',np.subtract(x,y))

data x 
 [5 6 7 8]
data y 
 [1 2 3 4]
method 1 
 [4 4 4 4]
method 2 
 [4 4 4 4]


**Multiplication**

![](https://i.imgur.com/j4wjueq.jpg)

In [ ]:
import numpy as np
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print('data x \n',x)
print('data y \n',y)
# Tích các phần tử tương ứng giữa x và y
print('method 1 \n',x*y)
print('method 2 \n',np.multiply(x,y))

data x 
 [1 2 3 4]
data y 
 [5 6 7 8]
method 1 
 [ 5 12 21 32]
method 2 
 [ 5 12 21 32]


**Division**


![](https://i.imgur.com/efDNrOA.jpg)

In [ ]:
import numpy as np
x = np.array([5,6,7,8])
x = np.array([1,2,3,4])
print('data x \n',x)
print('data y \n',y)
# Phép chia các từng phần tương ứng x cho y 
print('method 1 \n',x/y)
print('method 2 \n',x//y)
print('method 3 \n',np.divide(x,y))

data x 
 [1 2 3 4]
data y 
 [5 6 7 8]
method 1 
 [0.2        0.33333333 0.42857143 0.5       ]
method 2 
 [0 0 0 0]
method 3 
 [0.2        0.33333333 0.42857143 0.5       ]


**Square root**


![](https://i.imgur.com/0XVFNBB.jpg)

In [ ]:
import numpy as np 
data = np.array([1,2,3,4])
print('data \n',data)
# Căn bặc hai từng phần tử trong data
print('sqrt \n',np.sqrt(data))

data 
 [1 2 3 4]
sqrt 
 [1.         1.41421356 1.73205081 2.        ]


**Inner product**


![](https://i.imgur.com/bs9tIbs.jpg)

In [ ]:
import numpy as np 
v = np.array([1,2])
w = np.array([2,3])
# Tính inner product giữa v và w
print('method 1 \n',v.dot(w))
print('method 2 \n',np.dot(v,w))

method 1 
 8
method 2 
 8


**Vector-matrix multiplication**



![](https://i.imgur.com/PlXaXP6.jpg)

In [ ]:
import numpy as np
X = np.array([[1,2],[3,4]])
v = np.array([1,2])
print('matrix X \n',X)
print('vector v \n',v)
# Phép nhân giữa ma trận và vector
print('mehod 1 : X.dot(v)  \n',X.dot(v))
print('mehod 2 : v.dot(X)  \n',v.dot(X))

matrix X 
 [[1 2]
 [3 4]]
vector v 
 [1 2]
mehod 1 : X.dot(v)  
 [ 5 11]
mehod 2 : v.dot(X)  
 [ 7 10]


**Matrix-matrix multiplication**


![](https://i.imgur.com/mtv93Gz.jpg)

In [ ]:
import numpy as np
X = np.array([[1,2],[3,4]])
Y = np.array([[2,3],[2,1]])
# C1 Phép nhân giữa hai ma trận 
print('method 1 \n',X.dot(Y))
print('method 1 \n',Y.dot(X))
#C2  Phép nhân giữa hai ma trận 
print('method 2 \n',np.dot(X,Y))
print('method 2 \n',np.dot(Y,X))

method 1 
 [[ 6  5]
 [14 13]]
method 1 
 [[11 16]
 [ 5  8]]
method 2 
 [[ 6  5]
 [14 13]]
method 2 
 [[11 16]
 [ 5  8]]


**Transpose**


![](https://i.imgur.com/85THJ95.jpg)

In [ ]:
import numpy as np
X = np.array([[1,2],[3,4]])
print(X)
#Chuyển vị
print(X.T)

[[1 2]
 [3 4]]
[[1 3]
 [2 4]]


**Summation**


![](https://i.imgur.com/rz0ncFa.jpg)

In [ ]:
import numpy as np
X = np.array([[1,2],[3,4]])
#Tổng các phần tử của mảng 
print(np.sum(X))
#Tính tổng các phần tử theo từng cột
print(np.sum(X,axis=0))
#Tính tổng theo từng dòng 
print(np.sum(X,axis=1))

10
[4 6]
[3 7]


**Max and min**


![](https://i.imgur.com/diGN2yk.jpg)

In [ ]:
import numpy as np
data = np.array([1,2,3])
print(data.max())
print(data.min())

data2d = np.array([[1,2],[3,4],[5,6]])
print(data2d.max(axis=0))
print(data2d.max(axis=1))
print(data2d.min(axis=1))
print(data2d.min(axis=1))

3
1
[5 6]
[2 4 6]
[1 3 5]
[1 3 5]


#**D.Broadcasting**


**Vector and a scalar**


![](https://i.imgur.com/Hj98wxI.jpg)

In [29]:
import numpy as np
#create data
data = np.array([1,2,3])
factor = 2

#broadcasting 
result_multiplication = data*factor
result_minus = data - factor

print(data)
print(result_multiplication)
print(result_minus)

[1 2 3]
[2 4 6]
[-1  0  1]


**Matrix and vector**

![](https://i.imgur.com/qraZkMh.jpg)

In [ ]:
import numpy as np
X = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
v = np.array([1,0,1])
Y = X + v
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


#**E.Data Processing**


**Text data** 

![](https://i.imgur.com/vSAnsB0.jpg)

![](https://i.imgur.com/w6RCoyX.jpg)



*   **IRIS data**


In [ ]:
from google.colab import auth
auth.authenticate_user()
from pydrive.drive import GoogleDrive
from pydrive.auth import GoogleAuth
from oauth2client.client import GoogleCredentials
import numpy as np
import numpy.core.defchararray as np_f

gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)
#đây là chuỗi ký tự chữ và số dài xuất hiện khi bạn nhấp vào "lấy liên kết để chia sẻ"
myfile = drive.CreateFile({'id': '1AhaTBU0uGWiEaij7ckjerqHKl2u7xz-n'})
myfile.GetContentFile('iris_full.csv')
# Lấy các đặc trưng và lưu vào biến X
X = np.genfromtxt('iris_full.csv',delimiter=',',dtype='float',usecols=[0,1,2,3],skip_header=1)
print(X.shape)
# Lấy các species và lưu vào biến y
y = np.genfromtxt('iris_full.csv',delimiter=',',dtype='str',usecols=4,skip_header=1)
#thay chuỗi bằng số 
categories = np.unique(y)
for i in range(categories.size):
  y = np_f.replace(y,categories[i],str(i))
# đưa về kiểu float :
y = y.astype('float')
print(y)

(150, 4)
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2. 2.
 2. 2. 2. 2. 2. 2.]


**Image Data**


*   **Grayscale images**

    






![](https://i.imgur.com/upZZhv5.jpg)

*   **Image Classification: Image Data**

![](https://i.imgur.com/VIf3cQV.jpg)

![](https://i.imgur.com/HdcZAAA.jpg)

#**OpenCV**

![](https://i.imgur.com/aVxWovj.jpg)

![](https://i.imgur.com/JFLk2yd.jpg)